name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Archive Release - Fiefox
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release-${{GITHUB_SHA}}-firefox.xpi'
          exclusions: 'dist/*'

      - name: Archive Release - Chrome
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release-${{GITHUB_SHA}}-chrome.xpi'
          exclusions: 'dist/*'
